[package]
name = "rocker"
version = "0.2.2"
authors = ["Maxim Molchanov <m.molchanov@vonmo.com>"]
license = "MIT/Apache-2.0"

[lib]
name = "rocker"
crate-type = ["dylib"]

[dependencies]
erlang_nif-sys = "=0.6.4"
lazy_static = "=1.1.*"
rustler = "=0.18.0"
rocksdb = { git = "https://github.com/Elzor/rust-rocksdb.git", branch = "stable_5.14.2" }