[package]
name = "rocker"
version = "0.1.0"
authors = ["Maxim Molchanov <m.molchanov@vonmo.com>"]
license = "MIT/Apache-2.0"

[lib]
name = "rocker"
crate-type = ["dylib"]

[dependencies]
erlang_nif-sys = ">=0.6.3"
lazy_static = "0.2.*"
rustler = ">=0.13.0"
#rocksdb = "0.9.1"
rocksdb = { git = "https://github.com/Elzor/rust-rocksdb.git", branch = "master" }